language: python
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.5
      env: DEPLOY_DOCS=ON
    - python: 3.6

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install --upgrade wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install twine
  - pip install sphinx
  - pip install numpydoc
  - pip install sphinx_rtd_theme
  - pip install matplotlib
  - pip install python-coveralls
  - python setup.py build
  - pip install pytest>=3.6 pytest-cov pep8 pytest-pep8

script:
  - |
    if [[ "${DEPLOY_DOCS}" == "ON" ]]; then
        cd docs
        make html
        touch _build/html/.nojekyll
    fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_KEY
    local_dir: docs/_build/html
    on:
        branch: master
        condition: $DEPLOY_DOCS == ON

deploy:
  provider: pypi
  user: "__token__"
  password: pypi-AgEIcHlwaS5vcmcCJDczOWRiM2RlLTliYWMtNDAzOS04NWVhLTk2NTczZjliOGU4MwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgiMZdcA0eaDiM6_VaQjXQd5oYgHcORJwKx2-gK349_Zc
